### PR TITLE
Laravel 6 compatibility

### PR DESCRIPTION
**Pull request by emilsundberg**
Makes it possible to install this package on Laravel 6

### CODE REVIEW

**Comment by BrandonSurowiec** [comment]
@emilsundberg To make the tests pass `RollbarTest.php` needs to be updated to use the new signature:

```
protected function setUp(): void {

}
```

**Comment by BrandonSurowiec** [comment]
@ArturMoczulski  Laravel 6 was released yesterday. Can we get this PR merged in once ready and a new release tagged?

**Comment by jonnott** [comment]
+1 for merging this so I can update to L6.0 :)

**Comment by jonnott** [comment]
> While you wait it is possible to add my repository in your `composer.json`

Amazing - that's exactly what I've done :)

**Comment by jonnott** [comment]
> > While you wait it is possible to add my repository in your `composer.json`
> 
> Amazing - that's exactly what I've done :)

However, I now have this problem https://github.com/rollbar/rollbar-php/issues/460
...due to composer resolving to v1.8.0 of rollbar/rollbar-php

Seems like we really need Rollbar to pull their finger out and update *both* these libs :(

**Comment by emilsundberg** [comment]
@jonnott A temporary fix I use is to requiring monolog/monolog ^1 in my `composer.json`

```
"require": {
   [..]
   "monolog/monolog": "^1"
},
```

**Comment by jonnott** [comment]
Yes, that’s what I’ve done too!

**Comment by swilla** [comment]
There is anything I can do to help get this PR in shape where it can be merged?

**Comment by jonnott** [comment]
> There is anything I can do to help get this PR in shape where it can be merged?

There is nothing further that needs doing. The Codacy/PR Quality Review is objecting to the Arr::pull() calls - but that's the only way to do it now that the global helper equivalent array_pull() has been removed from Laravel.

Someone from Rollbar just needs to merge the PR, but they're ignoring these threads.

I've even tried asking Rollbar support directly, but to no avail so far.

Please, everyone who needs this merged to update to L6.0, just open a support ticket to Rollbar about it until they pay attention!

**Comment by jonnott** [comment]
Bugsnag are all over L6.0 compatibility already .. https://github.com/bugsnag/bugsnag-laravel/releases

Time to jump ship?

**Comment by wyoumans** [comment]
would love to see this merged.

**Comment by jonnott** [comment]
Think you’ll need to open a support ticket to Rollbar support for them to pay any attention whatsoever..

**Comment by ArturMoczulski** [comment]
thanks @jonnott for being very adamant on merging this. I'm in the process of getting this released. Should be out soon

**Comment by jonnott** [comment]
Great, thanks. Having monolog ^2.0 support in rollbar-php would also be a bonus.

**Comment by Arkanius** [comment]
Is this package abandoned? As @jonnott said, time to jump ship?

**Comment by emilsundberg** [comment]
I got an email from their support yesterday:

> Our development team is currently in the process of merging this PR. I can provide you with updates as they become available. We appreciate your patience as we work on this.

**Comment by ArturMoczulski** [comment]
@jonnott I'll do my best to have the monolot ^2.0 support released as well

@Arkanius as you can see by the popularity of the thread, very much alive :)

**Comment by Arkanius** [comment]
I'm not sure about ir. This thread has almost 30 days. Some people already forked the repo and added the compatibility. I was just thinking about to drop rollbar and go to another service (sentry, bugsnag)

**Comment by jonnott** [comment]
> I'm not sure about ir. This thread has almost 30 days. Some people already forked the repo and added the compatibility. I was just thinking about to drop rollbar and go to another service (sentry, bugsnag)

 @brianr .. the people are voting with their feet :)

**Comment by jonnott** [comment]
So now it's merged .. how does it get released?

**Comment by jopacicdev** [comment]
Hi @ArturMoczulski, when can we expect this to be released?

**Comment by ArturMoczulski** [comment]
@jopacicdev working right now on getting it released asap

**Comment by jonnott** [comment]
> @jopacicdev working right now on getting it released asap

What's stopping it? Does somebody from Rollbar Inc. need to approve it?

**Comment by ArturMoczulski** [comment]
As you know there is Laravel 6 and Monolog 2 PRs that have been merged. I'm working on having both of those released, but I also need to make sure that the release passes on PHP >= 5.6. Unfortunately, currently, our builds are not passing due to incompatibility between PHP versions, monolog versions and laravel versions. I'm working on making everything green across the build matrix in Travis CI, but it's more complicated than just releasing the packages. I first need to fix incompatibilities.

**Comment by jonnott** [comment]
> @jonnott I'll do my best to have the monolog ^2.0 support released as well

Put in a PR for that here: https://github.com/rollbar/rollbar-php/pull/468/

**Comment by ArturMoczulski** [comment]
Yes, and as you can see in Travis that PR is not passing the builds. So I need to fix the problems with it, as well as problems with the Laravel 6 and PHP versions before I can get it out to the public.

I assure you it's a high priority item we are working on and I'm doing my best to get it out to you as soon as I can

**Comment by jonnott** [comment]
monolog 1.x requires PHP >=5.3.0

monolog 2.x requires PHP >= 7.2

.. so if a package supports either monolog 1.x OR 2.x, that should all work out, right?

**Comment by ArturMoczulski** [comment]
Monolog 2 is backward incompatible. That's why it's a major bump version. It means that we need to adjust our code in the SDK to support Monolog 2 while also keeping support for Monolog 1 conditionally depending on what version you are using.

There are also other problems with the builds I'm trying to figure out. There seems to be an incompatibility between Mockery and some of the Monolog handler definitions currently.

**Comment by ArturMoczulski** [comment]
@jonnott having that said I hugely appreciate your level of effort and engagement in the community behind our SDKs :) it's great to see you can't wait to put your hands on the new release. I'll be publishing it as soon as it's ready

**Comment by ghostal** [comment]
Feel a bit bemused that people using versions of PHP that are officially supported are having to wait for the tests to pass for `>=5.6`, which reach EOL 9 months ago. In fact, the `composer.json` for 4.x has `"php": ">=7.0",` in it, so I see even less reason why `>=5.6` tests have to pass.

Am I missing something here?

**Comment by drbyte** [comment]
Why not just tag `5.0` which forces the same supported PHP version/s (and monolog) as Laravel 6.0 does? 
And then leave the older 4.x/etc versions to work with older PHP and older monolog dependencies?

**Comment by ArturMoczulski** [comment]
@drbyte that might be the best solution, I've been looking into feasibility of doing this

**Comment by ghostal** [comment]
Sorry, deleted my previous comment here having found that the issue thread was more recently active.

Was just bemused at requiring tests to pass for PHP `>=5.6` when it's no longer supported and the `composer.json` for 4.x requires PHP `>=7.0`.

I gather though that Monolog 2.x, as required by Laravel 6, isn't currently supported, and that that's what is currently holding things up. Is that correct?

**Comment by ArturMoczulski** [comment]
Yes. This merge is dependent on a bigger update to the `rollbar-php` repo which has been a big task to do and is still not completed. However, it is my number priority right now and should I be able to release very soon. Either by maintaining our current approach of fully supporting PHP >= 5.3 or no. This is currently in debate.

**Comment by jonnott** [comment]
Can support for both older and newer PHP versions not be achieved with some if statements?

**Comment by jonnott** [comment]
What I mean is:

Make the monolog dependency in rollbar-php be ”^1.0|^2.0”

Then in the code say “if” monolog 1.x is loaded, do this ... “else if” 2.x is loaded, do it differently.

Therefore you support all PHP versions that either monolog 1.x or 2.x

If I’m not mistaken, that is exactly the approach the Laravel framework itself is using with monolog at this point (6.x and earlier 5.x versions too?)

Solved ...?

**Comment by ArturMoczulski** [comment]
The differences in between Monolog 1 and Monolog 2 are based on language syntax changes which make the files imparsable by both PHP 5 and PHP 7. Otherwise it would a great suggestion @jonnott 

I'm putting together the release right now though, so should be out in a couple of hours

**Comment by jonnott** [comment]
Ah, that is a pain.

Does anyone know if composer has a way of specifying a joint dependency pairing, e.g:

php ^5.3 && monolog ^1.0
OR
php ^7.0 && monolog ^2.0

Too optimistic? ;)

**Pull request merged**
