### PR TITLE
Properly handle Laravel model for "person_fn".

### PR DESCRIPTION
**Pull request by MeekLogic**
Fixes – #73

### CODE REVIEW

**Comment by MeekLogic** [comment]
Fixes – #73

**Comment by jessewgibbs** [comment]
@meeklogic thanks for the PR.

@ArturMoczulski can you review?

**Comment by MeekLogic** [comment]
I am still getting an error in my API controllers (haven't fully debugged it yet).

I think `Rollbar\\DataBuilder->getPerson()` runs prior to recieving context from this package. Thus it calls 'person_fn' itself and gets an object.

**Comment by ArturMoczulski** [comment]
@MeekLogic what error are you getting in your API controllers?

**Comment by MeekLogic** [comment]
> @MeekLogic what error are you getting in your API controllers?

#73 
`Argument 4 passed to Rollbar\Payload\Person::__construct() must be of the type array or null, object given, called in C:\inetpub\wwwroot\oim-laravel\vendor\rollbar\rollbar\src\DataBuilder.php on line 894`

The above PR fixed it but for some reason I have noticed that it still occurs on a specific API route. It was an image upload route and the error that I was actually having was with NTFS permissions.

I have fixed the NTFS issue and have not noticed an issue since.

This may or may not be caused by an "API" route or by a low level error that occurs in Laravel prior to hooking Rollbar.

However, I do not currently have enough experience with Laravel to make a proper assumption as to the root cause.

**Comment by ArturMoczulski** [comment]
LGTM. Merging into `master` and checking if the change can be reproduced in release line `v3.*`.

I created an additional issues for the context problem here: https://github.com/rollbar/rollbar-php-laravel/issues/76

**Pull request merged**
