### PR TITLE
Fixed MonologHandler conflict while using rollbar agent

### PR DESCRIPTION
**Pull request by Lukasz93P**
## Description of the change

Resolver handler conflict while using rollbar agent handler. [Bug which was describer here](https://github.com/rollbar/rollbar-php-laravel/issues/85)

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)

## Related issues

> Bug [#85 ](https://github.com/rollbar/rollbar-php-laravel/issues/85) 

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [x]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by Lukasz93P** [comment]
@bishopb @brianr @waltjones @jenssegers @ArturMoczulski can you please review and merge this change?
I know that this is maybe not ideal but I'm in a hurry I need working laravel rollbar agent for my production app ASAP.

**Comment by brianr** [comment]
Hi @Lukasz93P, we will aim to get this reviewed soon, but probably not until next week. The fastest path to resolve your production app issue is probably to install your branch directly, something like this: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository (note you'll probably need to rename the branch to start with `dev-`).

**Comment by Lukasz93P** [comment]
@brianr I know that but I didnt want to have to do this.
Thanks for info when somebody will look at this 🙂

**Comment by Lukasz93P** [comment]
@brianr can someone review this pr ?

**Comment by bishopb** [comment]
Thanks for the contribution, @Lukasz93P. I've taken this in a slightly different direction. Would you mind trying [Pull Request #109](https://github.com/rollbar/rollbar-php-laravel/pull/109) in your environment to see if it works for you?

**Comment by Lukasz93P** [comment]
@bishopb yes, I will try but I need at least few days for this.

**Comment by bishopb** [comment]
Thank you again for your contribution. I'm closing this one in favor of Pull Request #109. A new release will be cut soon.

**Comment by Lukasz93P** [comment]
@bishopb unfortunately this solution also causes an error - `Attempt to read property "session" on null (Most recent call first) - /app/vendor/rollbar/rollbar-laravel/src/MonologHandler.php line 62`.
When I changed package version to my closed pull request in the same environment, then it works, so I'm still unable to use official version instead of my own fork.

**Comment by bxsx** [comment]
> @bishopb unfortunately this solution also causes an error - `Attempt to read property "session" on null (Most recent call first) - /app/vendor/rollbar/rollbar-laravel/src/MonologHandler.php line 62`. When I changed package version to my closed pull request in the same environment, then it works, so I'm still unable to use official version instead of my own fork.

This seems to be related to #106 which I just merged. Would you mind giving it a try?

**Comment by Lukasz93P** [comment]
Hi @bxsx, any update here? Can my PR be merged or maybe you have better solution(mentioned above is not worki g) ?

**Comment by cyrusradfar** [comment]
Wasn't the issue resolved here https://github.com/rollbar/rollbar-php-laravel/issues/85#issuecomment-810717078

**Comment by danielmorell** [comment]
@Lukasz93P what version of `rollbar/rollbar-laravel` are you running?

**Pull request closed without merging**
