### PR TITLE
Add laravel 7.x support

### PR DESCRIPTION
**Pull request by bastien-phi**
Add support for Laravel 7.x

### CODE REVIEW

**Comment by jasonmccreary** [comment]
If you let me know when you merge/tag this and I'll update the [Laravel 7.x Shift](https://laravelshift.com/upgrade-laravel-6.x-to-laravel-7.x) to automate the constraint update for your users.

**Comment by jonnott** [comment]
+1 for merging this. Today is Laravel 7 launch day, and nobody using this lib will be able to upgrade yet.

**Comment by jonnott** [comment]
@ArturMoczulski ?

**Comment by jonnott** [comment]
@emilsundberg

**Comment by jonnott** [comment]
Cool, now we just need a release..

**Comment by waltjones** [comment]
Should be good to go.

https://packagist.org/packages/rollbar/rollbar-laravel

**Comment by jasonmccreary** [comment]
Thanks all. I have update Shift to automate the new `^6.0` constraint for users of this package.

**Comment by jonnott** [comment]
Thanks all. About to push my Laravel 7.x updated app to production :)

**Pull request merged**
