### PR TITLE
Only include sessions data when sessions are available

### PR DESCRIPTION
**Pull request by erwineverts**

### CODE REVIEW

**Comment by neochief** [comment]
+1

**Comment by waltjones** [comment]
@erwineverts Thank you for the PR. The fix looks fine. Can you take a look at the failing test?

**Comment by waltjones** [comment]
Maybe all it needs is rebase master.

**Comment by tristanjahier** [comment]
OK this seems to be the same as #90.
It would fix the integration with Laravel Zero as well.

**Comment by darkcarnage** [comment]
Any plans to merge this PR ? That obviously solves the problem with Lumen.

**Review by villaflor — APPROVED** [review]
This is looking good. It is make sense that checking the session if set first before getting all the session in case that the application is Laravel Lumen.

**Comment by tristanjahier** [comment]
@waltjones Any chance that this is accepted and merged?

**Review by villaflor — APPROVED** [review]

**Comment by bxsx** [comment]
Hey @erwineverts @neochief @darkcarnage @villaflor @tristanjahier 

Seems that the branch is no longer available but I just merged #106 which duplicates this PR.

**Comment by erwineverts** [comment]
@bxsx Thank you! I've been using Sentry for the past couple of years. But great to see progress on this bug.

**Comment by bxsx** [comment]
Thanks @erwineverts 
You can look at Rollbar again when you find spare time. There have been many enhancements and new features in recent years that may interest you.

Cheers

**Pull request closed without merging**
