### PR TITLE
Laravel 9 Support

### PR DESCRIPTION
**Pull request by joelbutcher**
Adds Laravel 9 Support to CI actions and composer

### CODE REVIEW

**Comment by jonnott** [comment]
@joelbutcher See https://github.com/rollbar/rollbar-php-laravel/pull/121

**Comment by cyrusradfar** [comment]
@joelbutcher hi, we're getting someone to review this and follow up. We see you and thank you!

**Comment by jamesaspence** [comment]
ngl, I'm eagerly watching this PR because laravel 9 support is the only thing holding us back from an upgrade of our API 😂

**Comment by joelbutcher** [comment]
@cyrusradfar what testing do you think needs to be completed on this before being merged? I can spin up a working Laravel 9 app with routes for logging to rollbar within minutes. If required, I can provide an example repo

**Comment by s5w95** [comment]
Quick workaround until they merge this PR

composer.json

```
"require": {
   ...
  "rollbar/rollbar-laravel": "dev-feature/laravel-9-support",
  ...
},
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/joelbutcher/rollbar-php-laravel"
        },
],
...
```

works for me fine on laravel 9

**Review by danielmorell — APPROVED** [review]
This looks good to me. Thank you @joelbutcher for your work on this!

**Comment by jonnott** [comment]
@cyrusradfar Great. Can we now also merge #93 and then get a new major version tagged asap? The clock is ticking for myself and many other it would seem..

**Comment by cyrusradfar** [comment]
@jonnott are you impacted by #93? 

Based on our review merging #93 would actually be a step backwards. Monolog\Handler\RollbarHandler is the correct reference and Rollbar\Monolog\Handler\RollbarHandler is the old one.

W.r.t tagging a release, we'll do so -- thank you.

**Comment by jonnott** [comment]
> @jonnott are you impacted by #93?
> 
> Based on our review merging #93 would actually be a step backwards. Monolog\Handler\RollbarHandler is the correct reference and Rollbar\Monolog\Handler\RollbarHandler is the old one.
> 
> W.r.t tagging a release, we'll do so -- thank you.

Sorry, I meant https://github.com/rollbar/rollbar-php-laravel/pull/94 (PR 94) rather than issue 93..

**Comment by jonnott** [comment]
If https://github.com/rollbar/rollbar-php-laravel/pull/94 doesn't need merging, can the PR be closed?

**Comment by cyrusradfar** [comment]
Yes, it should be, let me put some explanation there as to why for the folks who've been waiting.

**Comment by danielmorell** [comment]
@jonnott thank you for keeping on top of things here! We have released [v7.1.0](https://github.com/rollbar/rollbar-php-laravel/releases/tag/v7.1.0) and it includes Laravel 9 support as added by @joelbutcher. We deeply appreciate both of you and your perseverance on this update!

**Pull request merged**
