### PR TITLE
Laravel 9.x support (8.0 release?)

### PR DESCRIPTION
**Pull request by jonnott**
## Description of the change

Support illuminate/support 9.x, therefore being Laravel 9.x compatible (whilst still compatible with older Laravel versions too). Last update to 7.0 of this package only needed a similar change to composer.json, so just getting the ball rolling. I can't spot anything obviously different in illuminate/support 9.x which would break anything this package is using.. https://github.com/illuminate/support/compare/8.x...9.x

## Type of change

- [x] Maintenance
- [x] New release

## Related issues

See comment here https://github.com/rollbar/rollbar-php-laravel/issues/120

### CODE REVIEW

**Comment by niektenhoopen** [comment]
@bishopb Any chance that you might be able to merge this? It's only a composer requirement change and then we can update to Laravel 9.

**Comment by Julian-Louis** [comment]
> @bishopb Any chance that you might be able to merge this? It's only a composer requirement change and then we can update to Laravel 9.

I just contacted their support to ask them to merge it

**Comment by jonnott** [comment]
> I just contacted their support to ask them to merge it, I hope they will do it

Hopefully, yes. I recall last major Laravel version, getting Rollbar to pay attention to my PR was a long and tedious process!

**Comment by jonnott** [comment]
> > I just contacted their support to ask them to merge it, I hope they will do it
> 
> Hopefully, yes. I recall last major Laravel version, getting Rollbar to pay attention to my PR was a long and tedious process!

@niektenhoopen @Julian-Louis In the meantime, I have a patched version at https://github.com/jonnott/rollbar-php-laravel/commits/patch-1

**Comment by joelbutcher** [comment]
@jonnott You also need to update the CI pipeline files to make sure the tests are covered for Laravel 9 and PHP 8

**Pull request closed without merging**
